# Generated by Django 5.1.4 on 2025-05-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='some_field',
        ),
        migrations.AddField(
            model_name='news',
            name='short_content_eng',
            field=models.TextField(default=True, help_text='Нельзя оставить пустым', verbose_name='Текст новости на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='short_content_rus',
            field=models.TextField(default=False, help_text='Нельзя оставить пустым', verbose_name='Текст новости на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='short_content_tkm',
            field=models.TextField(default=True, help_text='Нельзя оставить пустым', verbose_name='Текст новости на туркменском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='screenwriter',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='studiohistory',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
    ]
