# Generated by Django 5.1.4 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_film_some_field_news_short_content_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioHistorySSSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография')),
                ('text_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Информация о студии на русском')),
                ('text_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Информация о студии на английском')),
                ('text_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Информация о студии на туркменском')),
                ('creator_bio_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография создателя студии на русском')),
                ('creator_bio_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография создателя студии на английском')),
                ('creator_bio_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография создателя студии на туркменском')),
                ('found_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата основания студии')),
                ('creator_birth_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата рождения создателя')),
            ],
            options={
                'verbose_name': 'История студии в времена СССР',
                'verbose_name_plural': 'История студии в времена СССР',
            },
        ),
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_eng',
            field=models.TextField(help_text='Нельзя оставить пустым', verbose_name='описание новостей на английском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_rus',
            field=models.TextField(help_text='Нельзя оставить пустым', verbose_name='описание новостей на русском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_tkm',
            field=models.TextField(help_text='Нельзя оставить пустым', verbose_name='описание новостей на туркменском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_content_eng',
            field=models.TextField(help_text='Нельзя оставить пустым', verbose_name='Краткое описание новостей на английском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_content_rus',
            field=models.TextField(help_text='Нельзя оставить пустым', verbose_name='Краткое описание новостей на русском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_content_tkm',
            field=models.TextField(help_text='Нельзя оставить пустым', verbose_name='Краткое описание новостейна туркменском'),
        ),
        migrations.AlterField(
            model_name='screenwriter',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='studiohistory',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='media/images/', verbose_name='Фотография'),
        ),
    ]
