# Generated by Django 5.1.4 on 2025-05-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_studiohistorysssr_alter_actors_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiohistorysssr',
            name='creator_bio_eng',
        ),
        migrations.RemoveField(
            model_name='studiohistorysssr',
            name='creator_bio_rus',
        ),
        migrations.RemoveField(
            model_name='studiohistorysssr',
            name='creator_bio_tkm',
        ),
        migrations.RemoveField(
            model_name='studiohistorysssr',
            name='creator_birth_date',
        ),
    ]
