# Generated by Django 5.1.4 on 2025-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_sssr_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiohistory',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiohistorysssr',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='screenwriter',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='studiohistory',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='studiohistorysssr',
            name='image',
            field=models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
    ]
