# Generated by Django 5.1.4 on 2025-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_actors_image_base64_director_image_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='location_of_birth',
            field=models.CharField(default='Ashgabat', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='location_of_birth',
            field=models.CharField(default='Ashgabat', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateField(default='1990-05-07'),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='location_of_birth',
            field=models.CharField(default='Ashgabat', max_length=100),
        ),
    ]
