# Generated by Django 5.1.4 on 2025-05-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_actors_location_of_birth_director_location_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='screenwriters',
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriter',
            field=models.ForeignKey(blank=True, help_text='Выберите одного сценариста', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_written', to='films.screenwriter', verbose_name='Сценарист'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AlterField(
            model_name='film',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.AlterField(
            model_name='screenwriter',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.AlterField(
            model_name='studiohistory',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.AlterField(
            model_name='studiohistorysssr',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Выберите одного режиссёра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_directed', to='films.director', verbose_name='Режиссёр'),
        ),
    ]
