# Generated by Django 5.1.4 on 2025-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_film_screenwriters_film_screenwriter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='screenwriter',
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriters',
            field=models.ManyToManyField(related_name='films', to='films.screenwriter'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='films.director'),
        ),
    ]
