# Generated by Django 5.1.4 on 2025-05-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_remove_film_screenwriter_film_screenwriters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(help_text='Выберите только одного', related_name='films', to='films.director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='screenwriters',
            field=models.ManyToManyField(help_text='Выберите только одного', related_name='films', to='films.screenwriter'),
        ),
    ]
