# Generated by Django 5.1.4 on 2025-05-28 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_director_alter_film_screenwriters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='screenwriters',
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriter',
            field=models.ForeignKey(blank=True, help_text='Выберите одного сценариста', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_written', to='films.screenwriter', verbose_name='Сценарист'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AlterField(
            model_name='film',
            name='genre_eng',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Жанр фильма на английском'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Выберите одного режиссёра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_directed', to='films.director', verbose_name='Режиссёр'),
        ),
    ]
