# Generated by Django 5.1.4 on 2025-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_remove_film_screenwriters_film_screenwriter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Сюдв можно зашружать только видео', upload_to='static/video/', verbose_name='Поставтье сюда трилер')),
            ],
            options={
                'verbose_name': 'Трилер',
                'verbose_name_plural': 'Трилеры',
            },
        ),
    ]
