# Generated by Django 5.1.4 on 2025-05-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='description_eng',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='description_rus',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='description_tkm',
            new_name='description_tk',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='genre_eng',
            new_name='genre_en',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='genre_rus',
            new_name='genre_ru',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='genre_tkm',
            new_name='genre_tk',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name_eng',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name_rus',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name_tkm',
            new_name='name_tk',
        ),
        migrations.RemoveField(
            model_name='actors',
            name='location_of_birth',
        ),
        migrations.RemoveField(
            model_name='director',
            name='location_of_birth',
        ),
        migrations.RemoveField(
            model_name='screenwriter',
            name='location_of_birth',
        ),
        migrations.AddField(
            model_name='actors',
            name='place_of_birth_eng',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='actors',
            name='place_of_birth_rus',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='actors',
            name='place_of_birth_tkm',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='place_of_birth_eng',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='place_of_birth_rus',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='place_of_birth_tkm',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='place_of_birth_eng',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='place_of_birth_rus',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='place_of_birth_tkm',
            field=models.CharField(default='Turkmenistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
