# Generated by Django 5.1.4 on 2025-05-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_rename_description_eng_film_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='kadr1',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='actors',
            name='kadr2',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='actors',
            name='kadr3',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='actors',
            name='kadr4',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='director',
            name='kadr1',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='director',
            name='kadr2',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='director',
            name='kadr3',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='director',
            name='kadr4',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='kadr1',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='kadr2',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='kadr3',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='kadr4',
            field=models.ImageField(default='static/images/25.jpg', help_text='Нельзя оставить пустым!', upload_to='static/kadr/', verbose_name='Фотография'),
        ),
    ]
