# Generated by Django 5.1.4 on 2025-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_rename_name_ru_film_name_rus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='screenwriter',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='films.director'),
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriter',
            field=models.ManyToManyField(related_name='films', to='films.screenwriter'),
        ),
    ]
