# Generated by Django 5.1.4 on 2025-05-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_remove_film_director_remove_film_screenwriter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='director',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='film',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='screenwriter',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='studiohistory',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='studiohistorysssr',
            name='image_base64',
        ),
    ]
