# Generated by Django 5.1.4 on 2025-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_remove_actors_image_base64_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='ImagehistorySSSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Нельзя оставить пустым!', upload_to='static/images', verbose_name='Фотография')),
            ],
        ),
        migrations.RemoveField(
            model_name='studiohistorysssr',
            name='image',
        ),
        migrations.AddField(
            model_name='studiohistory',
            name='imagehistory',
            field=models.ManyToManyField(related_name='history', to='films.imagehistory'),
        ),
        migrations.AddField(
            model_name='studiohistorysssr',
            name='imagehistorysssr',
            field=models.ManyToManyField(related_name='historysssr', to='films.imagehistorysssr'),
        ),
    ]
