# Generated by Django 5.1.4 on 2025-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('biography', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('film_actor', models.TextField()),
            ],
        ),
    ]
