# Generated by Django 5.1.4 on 2025-05-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшого объема картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография актёра')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Имя актёра на русском')),
                ('name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Имя актёра на английском')),
                ('name_tkm', models.CharField(default='Atsyz', help_text='Нельзя оставить пустым', max_length=50, verbose_name='Имя актёра на туркменском')),
                ('surname_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Фамилия актёра на русском')),
                ('surname_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Фамилия актёра на английском')),
                ('surname_tkm', models.CharField(default='Atsyz', help_text='Нельзя оставить пустым', max_length=50, verbose_name='Фамилия актёра на туркменском')),
                ('father_name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество актёра на русском')),
                ('father_name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество актёра на английском')),
                ('father_name_tkm', models.CharField(default='Atsyz', help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество актёра на туркменском')),
                ('biography_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на русском')),
                ('biography_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на английском')),
                ('biography_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на туркменском')),
                ('year', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Основная категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшого объема картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография Кино')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=250, verbose_name='Название фильма на русском')),
                ('name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=250, verbose_name='Название фильма на английском')),
                ('name_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=250, verbose_name='Название фильма на туркменском')),
                ('description_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Описание фильма на русском')),
                ('description_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Описание фильма на английском')),
                ('description_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Описание фильма на туркменском')),
                ('actors', models.ManyToManyField(related_name='Films', to='films.actors')),
            ],
        ),
    ]
