# Generated by Django 5.1.4 on 2025-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name': 'Актеры'},
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшого объема картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография фильма')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=250, verbose_name='Название фильма на русском')),
                ('name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=250, verbose_name='Название фильма на английском')),
                ('name_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=250, verbose_name='Название фильма на туркменском')),
                ('description_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Описание фильма на русском')),
                ('description_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Описание фильма на английском')),
                ('description_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Описание фильма на туркменском')),
                ('actors', models.ManyToManyField(related_name='Films', to='films.actors')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
