# Generated by Django 5.1.4 on 2025-05-13 10:14

import django.db.models.deletion
import films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_actors_options_film_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на русском')),
                ('name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на английском')),
                ('name_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на туркменском')),
                ('surname_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на русском')),
                ('surname_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на английском')),
                ('surname_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на туркменском')),
                ('father_name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на русском')),
                ('father_name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на английском')),
                ('father_name_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на туркменском')),
                ('biography_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на русском')),
                ('biography_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на английском')),
                ('biography_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на туркменском')),
                ('birth_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
            },
            bases=(models.Model, films.models.ImageProcessingMixin),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('title_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=200, verbose_name='Заголовок новости на русском')),
                ('title_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=200, verbose_name='Заголовок новости на английском')),
                ('title_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=200, verbose_name='Заголовок новости на туркменском')),
                ('content_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Текст новости на русском')),
                ('content_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Текст новости на английском')),
                ('content_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Текст новости на туркменском')),
                ('publication_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=(models.Model, films.models.ImageProcessingMixin),
        ),
        migrations.CreateModel(
            name='Screenwriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на русском')),
                ('name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на английском')),
                ('name_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на туркменском')),
                ('surname_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на русском')),
                ('surname_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на английском')),
                ('surname_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на туркменском')),
                ('father_name_rus', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на русском')),
                ('father_name_eng', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на английском')),
                ('father_name_tkm', models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на туркменском')),
                ('biography_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на русском')),
                ('biography_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на английском')),
                ('biography_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография на туркменском')),
                ('birth_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Сценарист',
                'verbose_name_plural': 'Сценаристы',
            },
            bases=(models.Model, films.models.ImageProcessingMixin),
        ),
        migrations.CreateModel(
            name='StudioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография')),
                ('image_base64', models.TextField(blank=True, help_text='Не трогать это поле!', null=True, verbose_name='Не трогать это поле!')),
                ('text_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Информация о студии на русском')),
                ('text_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Информация о студии на английском')),
                ('text_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Информация о студии на туркменском')),
                ('creator_bio_rus', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография создателя студии на русском')),
                ('creator_bio_eng', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография создателя студии на английском')),
                ('creator_bio_tkm', models.TextField(help_text='Нельзя оставить пустым', verbose_name='Биография создателя студии на туркменском')),
                ('found_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата основания студии')),
                ('creator_birth_date', models.DateField(help_text='Нельзя оставить пустым', verbose_name='Дата рождения создателя')),
            ],
            options={
                'verbose_name': 'История студии',
                'verbose_name_plural': 'История студии',
            },
            bases=(models.Model, films.models.ImageProcessingMixin),
        ),
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name': 'Актёр', 'verbose_name_plural': 'Актёры'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RenameField(
            model_name='actors',
            old_name='year',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='actors',
            name='father_name_eng',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на английском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='father_name_rus',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на русском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='father_name_tkm',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=50, verbose_name='Отчество на туркменском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='name_eng',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на английском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='name_rus',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на русском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='name_tkm',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Имя на туркменском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='surname_eng',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на английском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='surname_rus',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на русском'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='surname_tkm',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=100, verbose_name='Фамилия на туркменском'),
        ),
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='films.actors'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(help_text='Ставьте небольшие по объёму картинки. Нельзя оставить пустым!', upload_to='static/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_eng',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=200, verbose_name='Название фильма на английском'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_rus',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=200, verbose_name='Название фильма на русском'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_tkm',
            field=models.CharField(help_text='Нельзя оставить пустым', max_length=200, verbose_name='Название фильма на туркменском'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='films.director'),
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriters',
            field=models.ManyToManyField(related_name='films', to='films.screenwriter'),
        ),
    ]
